### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by SamoMelkonyan** [fluxtech-me/frontik#26]

**Comment by alexkharatyan** [comment]
Overlapping issue of datapicker-popper.

**Comment by Ruben-Arushanyan** [comment]
Please see: https://react-day-picker.js.org

**Comment by SamoMelkonyan** [comment]
- https://www.npmjs.com/package/react-datepicker?activeTab=dependencies
- https://reactdatepicker.com/#example-custom-time-input
- https://www.npmjs.com/package/react-day-picker
- https://react-day-picker.js.org/
- https://npmtrends.com/react-date-picker-vs-react-datepicker-vs-react-day-picker
